" Author: Jansen Mitchell
" Description: This is my personal .vimrc file.

syntax on " enables syntax highlighting

set number " enables line numbers

set hlsearch " highlights search results

set autoindent " indents a new line the same as the line just typed

" workaround for https://github.com/vim/vim/issues/1671 (bracketed paste issue)
if has('unix')
  let s:uname = system("echo -n \"$(uname)\"")
  if !v:shell_error && s:uname ==# 'Linux'
    set t_BE=
  endif
endif

" files to be spellchecked by default
autocmd BufRead,BufNewFile *.md setlocal spell
autocmd BufRead,BufNewFile *.fountain setlocal spell

set complete+=kspell " allows the use of ^N or ^P in insert mode for word completion

" adds text wraps to following file types at 80 characters
au BufRead,BufNewFile *.md setlocal textwidth=80
au BufRead,BufNewFile *.fountain setlocal textwidth=80

set history=200 " allows 200 commands to be recorded in command history

" vim-plug:
call plug#begin('~/.vim/plugged')

Plug 'junegunn/vader.vim' " a simple Vimscript test framework
Plug 'tpope/vim-surround' " provides mappings to easily delete, change, add paired suroundings

call plug#end()
